Update python-app.yml

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -40,17 +40,6 @@ jobs:
         known_hosts: ${{ secrets.KNOWN_HOSTS }}
         config: ${{ secrets.CONFIG }}
         if_key_exists: fail
-#     - name: Commit and push if changed
-#       run: |-
-#         rm README.md
-#         today=$(date "+%Y/%m/%d")
-#         echo ":white_check_mark: ${today}" > README.md
-#         git diff
-#         git config --global user.email "actions@users.noreply.github.com"
-#         git config --global user.name "README-bot"
-#         git add README.md
-#         git commit -m "Updated content" || exit 0
-#         git push
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
@@ -71,4 +60,15 @@ jobs:
         DATEQSTAT: ${{ secrets.DATEQSTAT }}
 
       run: |
-        python bot.py
+        max_attempts=3
+        attempt=1
+        while [ $attempt -le $max_attempts ]; do
+          echo "Attempt $attempt of $max_attempts"
+          python bot.py && break
+          attempt=$((attempt + 1))
+          sleep 5 # wait for 5 seconds before retrying
+        done
+        if [ $attempt -gt $max_attempts ]; then
+          echo "All attempts failed"
+          exit 1
+        fi
